bot_name: _bot
debug: true
timeoutMs: 60000

auth:
  bot_token:
  chatgpt_api_key:

completionParams: # from https://platform.openai.com/docs/api-reference/chat
  temperature: 1 # default 1
#  top_p: 1 # default 1

allowedPrivateUsers:
  - popstas

chats:
  - name: default
    id: 0
    progPrefix: бот, ты теперь
    progInfoPrefix: бот, начальные установки
    forgetPrefix: бот, забудь

  - name: Chat 1
    id:

  - name: user's direct
    username: popstas
    completionParams:
      model: gpt-4
      max_tokens: 4000
    buttons:
      - name: summarize
        prompt: |
          Summarize text. Text:

  - name: Chat 2
    id:
    prefix: бот
    systemMessage: |
      You are bot in chat 2
    completionParams:
      model: gpt-4
      max_tokens: 4000
      temperature: 0
