bot_name: _bot

auth:
  bot_token:
  chatgpt_api_key:

completionParams: # from https://platform.openai.com/docs/api-reference/chat
  debug: false
  temperature: 1 # default 1
#  top_p: 1 # default 1

chats:
  - name: Chat 1
    id:

  - name: Chat 2
    id:
    prefix: бот
